### ISSUE TITLE
Add validation compilation phase to ensure federated schema validity

### ISSUE THREAD

**Issue by kdawgwilk** [DivvyPayHQ/absinthe_federation#19]
It would be great if we had a schema phase that validated the federated aspects of the schema to give end users more insight into why the schema may be an invalid federated schema

**Comment by kdawgwilk** [comment]
I would refer mostly to the federation spec to determine which kinds of validations we want to enforce are in place https://www.apollographql.com/docs/federation/federation-spec an example would be that `@key` uses fields that actually exist on the GQL type so you can't have something like this
```elixir
object :product do
  key_fields("upc")
  field :id, non_null(:id)
end
```
Since the field `upc` doesnt exist on the type.  Another validation we could do is if a type is marked `@extends` the `@key(fields: "upc")` must also be `@external`

An example compliation validation phase you can reference would be this one from absinthe https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/phase/schema/validation/directives_must_be_valid.ex#L1

**Comment by scottming** [comment]
I'll take this.

**Comment by scottming** [comment]
Do we need to verify anything else now?

**Comment by maartenvanvliet** [comment]
> I didn't want to open a new issue since this one covers it. If we add duplicate directives for a field like `@deprecate` or `@tag`, it will break the composition. It will help to have a validation for making sure there are no duplicate directives for a field.

There's a validation in Absinthe to ensure that directives not marked as repeatable will return an error when applied multiple times. How does this break for you?

**Comment by kdawgwilk** [comment]
@maartenvanvliet maybe we run our phases after that validation phase? I wouldn't think we do but we are also doing some weird stuff like hand crafting the directive blueprint structs ourselves because of the lack of support in absinthe which may play into this

**Comment by kzlsakal** [comment]
I will try to replicate this in an example repo when I have a chance to demonstrate it. 

I know that it doesn’t get caught by Apollo’s managed schema checks either, but it breaks IntrospectAndCompose of Federation Gateway since 2.0.

**Comment by kzlsakal** [comment]
I pushed the branch where I replicated the issue here: https://github.com/kzlsakal/federation_duplicate_directives/tree/break-composition

If you start the `products` service it will compile and start successfully, but then starting the `gateway` will produce the following error:

```
IntrospectAndCompose failed to update supergraph with the following error: A valid schema couldn't be composed. The following composition errors were found:
        [products] The directive "@deprecated" can only be used once at this location.
Error: A valid schema couldn't be composed. The following composition errors were found:
        [products] The directive "@deprecated" can only be used once at this location.
```

**Comment by kdawgwilk** [comment]
Absinthe issue to add validation for this https://github.com/absinthe-graphql/absinthe/issues/1177

**Comment by maartenvanvliet** [comment]
Absinthe 1.7.1 is released with the fix for this. When I run the `break-composition` branch link above I get the following message:
```
== Compilation error in file lib/products_web/schema.ex ==
** (Absinthe.Schema.Error) Compilation failed:
---------------------------------------
## Locations
Column 0, Line 20

Directive `deprecated' cannot be applied repeatedly.
---------------------------------------
## Locations
Column 0, Line 19

Directive `deprecated' cannot be applied repeatedly.
```
So Absinthe now handles this correctly
