### ISSUE TITLE
Federation v2

### ISSUE THREAD

**Issue by kdawgwilk** [DivvyPayHQ/absinthe_federation#39]
What do we need to do to make this transition as smooth as possible?  v2 is backwards compatible but I think under the hood validations could change quite a bit.  Need to do some further investigation for what the implications of v2 are going to be.

**Comment by kdawgwilk** [comment]
Here is a post talking about supporting the federation 2 spec https://community.apollographql.com/t/apollo-federation-2-compatibility-showcasing-community-libraries/3272

There are a handful of directives that need to be added but it might make sense to add support for these using the new directive support that was added in absinthe instead of the custom macros absinthe_federation is currently using.  This would improve ergonomics and be in line with what absinthe would likely be supporting in the future

**Comment by dariuszkuc** [comment]
Should this issue be closed? Looks like library is supporting all v2.0 features (I opened up #72 and #73 for fed 2.3 support)

**Comment by kzlsakal** [comment]
Thank you @dariuszkuc! You're right, we can resolve this issue now. Also thanks for opening the issues related to fed 2.3.
