### ISSUE TITLE
`DataLoader` dependency conflict

### ISSUE THREAD

**Issue by chloe-meister** [DivvyPayHQ/absinthe_federation#83]
Hi there 👋 

I'm having a bit of an issue implementing the library in my project: we use the latest version of [DataLoader](https://github.com/absinthe-graphql/dataloader/blob/main/CHANGELOG.md), which conflict with the [requirements](https://github.com/DivvyPayHQ/absinthe_federation/blob/7b40c38c2191dce26840301cac6fafeb9bde93b4/mix.exs#L66) for `absinthe_federation`.

Would it be possible to allow both version ~> 1.0 and 2.0 as in [Absinthe](https://github.com/absinthe-graphql/absinthe/blob/cd4ab0ed54f6cb05507c52a28bbda04a9dbec04b/mix.exs#L78)?

It seems OK to me as you're not defining a custom DataLoader protocol anywhere. I'd be happy to implement it if you're ok with it of course.

**Comment by kdawgwilk** [comment]
Yeah loosening up those requirements seems okay to me

**Comment by chloe-meister** [comment]
Very good! I will get to it.

A bit of a sidetrack, but I've noticed while playing around the codebase that attempting to run tests with Absinthe 1.7 fails, most notably `test/absinthe/federation/notation_test.exs`. It looks to me like there might be an issue with the `link` macro under Absinthe 1.7.

I could try to have a better look and maybe fix it in the PR in which I would relax the `DataLoader` requirements? Else I'm happy to open a proper issue for this one as it's un-related.

**Comment by kzlsakal** [comment]
Hi! The bug that causes the error for the link directive was introduced by the absinthe version 1.7 and there's an issue about it: `https://github.com/absinthe-graphql/absinthe/issues/1279` (not linking directly so it doesn't tag this unrelated issue on it).

**Comment by chloe-meister** [comment]
Oh right, thanks for letting me know!

**Comment by chloe-meister** [comment]
I am closing this issue as it is being addressed 🙏
